GET /api/offers/8-ISnn/comments HTTP/1.1
Host: localhost:3000

###

POST /api/offers/8-ISnn/comments HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "id": "test-comment",
  "text": "Тест создания комментария."
}

###

DELETE /api/offers/8-ISnn/comments/test-comment HTTP/1.1
Host: localhost:3000
