GET /api/categories HTTP/1.1
Host: localhost:3000

###

GET /api/offers HTTP/1.1
Host: localhost:3000

###

GET /api/offers/8-ISnn HTTP/1.1
Host: localhost:3000

###

POST /api/offers HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "id": "test-id",
  "category": ["Тест"],
  "description": "Тест поста по POST-запросу",
  "picture": "item04.jpg",
  "title": "Тест создания поста.",
  "type": "offer",
  "sum": 42420
}

###

PUT /api/offers/test-id HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "category": ["Тест", "Тест2"],
  "description": "Тест обновления по PUT-запросу",
  "picture": "item01.jpg",
  "title": "Тест обновления поста.",
  "type": "offer",
  "sum": 97977
}

###

DELETE /api/offers/test-id HTTP/1.1
Host: localhost:3000
