GET / HTTP/1.1
Host: localhost:3000

###

GET /api/ HTTP/1.1
Host: localhost:3000

###

GET /api/offers/all HTTP/1.1
Host: localhost:3000

###

GET /api/offers/123 HTTP/1.1
Host: localhost:3000

###

POST /api/offers HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "category": ["Негативный тест"],
  "description": "Тест некорректного создания поста по POST-запросу",
  "title": "Тест создания поста без картинки и типа.",
  "sum": 42420
}

###

PUT /api/offers/123 HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "category": ["Тест", "Тест2"],
  "description": "Тест обновления несуществующего по PUT-запросу",
  "picture": "item01.jpg",
  "title": "Тест обновления несуществующего поста.",
  "type": "offer",
  "sum": 97977
}

###

DELETE /api/offers/123 HTTP/1.1
Host: localhost:3000

###

DELETE /api/offers HTTP/1.1
Host: localhost:3000
